model:
  name: 'Llama-2-7b_test'

training_parameters:
  lora_r: 64
  lora_alpha: 16
  lora_dropout: 0.1
  use_4bit: true
  bnb_4bit_compute_dtype: 'float16'
  bnb_4bit_quant_type: 'nf4'
  use_nested_quant: true
  output_dir: '/content/drive/MyDrive/results'
  num_train_epochs: 6
  fp16: true
  bf16: false
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  gradient_accumulation_steps: 1
  gradient_checkpointing: true
  max_grad_norm: 0.3
  learning_rate: 2e-4
  weight_decay: 0.001
  optim: 'paged_adamw_32bit'
  lr_scheduler_type: 'cosine'
  max_steps: -1
  warmup_ratio: 0.03
  group_by_length: true
  save_steps: 2000
  logging_steps: 25
  max_seq_length: null
  packing: false
  device_map:
    '': 0
